sonar.projectKey=Sonarqube-to-Jira-Automation
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.token=sqa_a9b93bce5999a8af9a165bed19f50d2b0f4ae389
sonar.exclusions=node_modules/**,dist/**,build/**
